### ISSUE TITLE
Instructor Feedback - Week 5 Hibernate one-to-many

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [MadJavaEntS20/humming-bird#3]
Great job implementing the generic dao and equals methods on your entities! You are cruising right along! 

- [ ] Two additional situations to cover with tests (if these are there and I overlooked them, let me know!) Test deleting a sighting that is associated with a user. Should the user be deleted? Verify that what should happen, does happen.  Likewise, if a User is deleted, should all of that user's sightings be deleted?

**Comment by emullendore** [comment]
I was able to successfully test deleting the sighting but maintaining the user. I've been trying to make the other work with no luck. I tried this but got a null pointer error on the last line.
`    @Test
    void deleteSuccess() {
        User userToDelete = (User)genericDao.getById(1);
        genericDao.delete(genericDao.getById(1));
        assertNull(genericDao.getById(1));
        assertNull(((User) genericDao.getById(1)).getSightings());
    }`

**Comment by pawaitemadisoncollege** [comment]
I think a null on the last line makes sense - genericDao.getById(1) should return a null, because the user has been deleted. Calling getSightings should produce a null pointer.  

Instead, what if you get the ids of the sightings for the user before deleting the user, then delete the user, then check if the sightings are still there by the ids that you retrieved earlier?

**Comment by emullendore** [comment]
Ok, I've pushed the code with this suggested test now.
